### ISSUE TITLE
Apply setup.py patch from AUR for Arch Linux

### ISSUE THREAD

**Issue by alkisg** [epoptes/epoptes#141]
While trying to install epoptes-client in Arch Linux, the following errors show up:

```shell
[administrator@archlinux epoptes-client]$ makepkg
...
Traceback (most recent call last):
  File "/home/administrator/epoptes-client/src/epoptes/setup.py", line 64, in <module>
    main()
  File "/home/administrator/epoptes-client/src/epoptes/setup.py", line 50, in main
    DistUtilsExtra.auto.setup(
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 405, in __add_imports
    if alias.name and __external_mod(cur_module, alias.name, attrs):
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 377, in __external_mod
    return 'dist-packages' in mod.__file__ or 'site-packages' in mod.__file__ or \
TypeError: argument of type 'NoneType' is not iterable
==> ERROR: A failure occurred in prepare().
    Aborting...
```

The good people at https://aur.archlinux.org/pkgbase/epoptes-client/ mention that a one-line patch is needed in setup.py, let's apply it and test it.

**Comment by alkisg** [comment]
The following commands allowed me to install epoptes-client in Arch Linux:

```shell
# sudo useradd -m administrator; su - administrator
sudo pacman -S python-distutils-extra inetutils git
git clone https://aur.archlinux.org/epoptes-client.git 
cd epoptes-client
# Remove `#tag=v${pkgver}` from PKGBUILD; after a new release that won't be needed
makepkg
sudo pacman -U epoptes-client-21.02-1-any.pkg.tar.zst  
echo '192.168.67.1  server' | sudo tee -a /etc/hosts
sudo epoptes-client -c
sudo systemctl enable epoptes-client
sudo systemctl start epoptes-client
```

**Comment by fottsia** [comment]
Confirming that this procedure works for me as well.
