### ISSUE TITLE
Problem packaging epoptes

### ISSUE THREAD

**Issue by anescdev** [epoptes/epoptes#145]
Hello, building epoptes on ArchLinux i receive that error, i don´t know how to fix them:

```
WARNING: the following files are not recognized by DistUtilsExtra.auto:
  data/epoptes.desktop.in
  po/README.md
  po/epoptes.pot
  twisted/plugins/epoptesd.py
twisted.plugins.epoptesd
ERROR: Python module netifaces not found
Traceback (most recent call last):
  File "/home/anes/Downloads/epoptes-client/src/epoptes/setup.py", line 64, in <module>
    main()
  File "/home/anes/Downloads/epoptes-client/src/epoptes/setup.py", line 50, in main
    DistUtilsExtra.auto.setup(
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 412, in __add_imports
    elif node.module and __external_mod(cur_module, node.module, attrs):
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 377, in __external_mod
    return 'dist-packages' in mod.__file__ or 'site-packages' in mod.__file__ or \
TypeError: argument of type 'NoneType' is not iterable
==> ERROR: Se produjo un fallo en prepare().
    Cancelando...
```

**Comment by alkisg** [comment]
Hi, the problem `ERROR: Python module netifaces not found` should be addressed by adding `python-netifaces` in your PKGBUILD file.

The epoptes-client PKGBUILD file in AUR seems to have all the proper dependencies already, see #141.

**Comment by anescdev** [comment]
I install all the dependencies an i receive that error now: 
`==> Creando el paquete: epoptes-client 21.02-1 (jue 18 nov 2021 13:50:11)
==> Comprobando dependencias mientras se ejecuta...
==> Comprobando dependencias mientras se compila...
==> Recibiendo las fuentes...
  -> Actualizando epoptes del repositorio git...
Extrayendo origin
==> Validando los archivos source con sha256sums...
    epoptes ... Omitido
==> Extrayendo las fuentes...
  -> Creando copia de trabajo de epoptes del repositorio git...
Reiniciar rama 'makepkg'
==> Iniciando prepare()...
twisted.plugins.epoptesd
running clean
WARNING: the following files are not recognized by DistUtilsExtra.auto:
  data/epoptes.desktop.in
  po/README.md
  po/epoptes.pot
  twisted/plugins/epoptesd.py
twisted.plugins.epoptesd
Traceback (most recent call last):
  File "/home/anes/Downloads/epoptes-client/src/epoptes/setup.py", line 64, in <module>
    main()
  File "/home/anes/Downloads/epoptes-client/src/epoptes/setup.py", line 50, in main
    DistUtilsExtra.auto.setup(
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 412, in __add_imports
    elif node.module and __external_mod(cur_module, node.module, attrs):
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 377, in __external_mod
    return 'dist-packages' in mod.__file__ or 'site-packages' in mod.__file__ or \
TypeError: argument of type 'NoneType' is not iterable
==> ERROR: Se produjo un fallo en prepare().
    Cancelando...`

**Comment by alkisg** [comment]
Please read the #141 issue that I mentioned, it address that exact problem.

**Comment by anescdev** [comment]
![img](https://user-images.githubusercontent.com/74417326/142423037-5aa4dc7c-df96-4d57-b39a-47e0afb145d5.png)

**Comment by anescdev** [comment]
Ok , finish all ty
