### ISSUE TITLE
Migrate from distutils to setuptools

### ISSUE THREAD

**Issue by alkisg** [epoptes/epoptes#193]
- [PEP632](https://peps.python.org/pep-0632/) mentions that distutils is deprecated and applications should instead move to setuptools.
- [GNOME](https://wiki.gnome.org/MigratingFromIntltoolToGettext) recommends to migrate from Intltool to Gettext.

In this issue we'll track the necessary code updates to achieve these.

```shell
# Regenerate POTFILES.in:
find .. -name '*.ui' -or -name '*.py' | sed 's|^[^/]*/||' | LANG=C sort >POTFILES.in

# Regenerate epoptes.pot:
xgettext --add-comments --directory=.. --default-domain=epoptes --output=epoptes.pot POTFILES.in

# The .po files are periodically downloaded from launchpad
```

TODO:

- Handle ../data/epoptes.desktop.in while avoiding `X-Ubuntu-Gettext-Domain=epoptes`.

**Comment by vagrantc** [comment]
python3-distutils is no longer present in Debian as of trixie, and epoptes fails to run:

    $ epoptes
    Traceback (most recent call last):
      File "/usr/bin/epoptes", line 20, in <module>
        from epoptes.ui import gui
      File "/usr/lib/python3/dist-packages/epoptes/ui/gui.py", line 8, in <module>
        from distutils.version import LooseVersion
    ModuleNotFoundError: No module named 'distutils'

**Comment by alkisg** [comment]
Hi Vagrant! Does `Depends: python3-distutils | python3-setuptools` work as a temporary solution, until this issue is properly implemented?

**Comment by vagrantc** [comment]
Installing python3-setuptools did work around the issue!

I think in Debian it might be preferable to do a versioned dependency such as python3-setuptools | python3-distutils ... possibly with some version constraints?

**Comment by alkisg** [comment]
In 2023 the Greek ministry of education stopped sponsoring LTSP and Epoptes, due to ...bureaucracy mistakes, not on purpose.
Until this is amended, I'd like to refrain from upstream development as much as possible, to avoid sending them the wrong signals.
Vagrant, would it be possible to resolve this with a Debian-specific patch? Or feel free to commit upstream whatever you like, that's also fine. Thank you!

**Comment by q2dg** [comment]
Hello. Is it already amended?
Thanks!
