### ISSUE TITLE
Uses deprecated "pipes" module

### ISSUE THREAD

**Issue by vagrantc** [epoptes/epoptes#216]
Lintian complained about the use of the pipes module:

    I: epoptes source: uses-deprecated-python-stdlib pipes (deprecated in Python 3.11, removed in Python 3.13) [epoptes/ui/gui.py:10]

https://peps.python.org/pep-0594/#deprecated-modules

**Comment by alkisg** [comment]
Thank you Vagrant, this can probably be replaced with https://docs.python.org/3/library/shlex.html#shlex.quote.

**Comment by jperon** [comment]
Trying epoptes today on Ubuntu plucky, I get this error:

```sh
Traceback (most recent call last):
  File "/usr/bin/epoptes", line 20, in <module>
    from epoptes.ui import gui
  File "/usr/lib/python3/dist-packages/epoptes/ui/gui.py", line 10, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```
