### ISSUE TITLE
Epoptes does not run under Linux Mint 24 because of deprecated "distutils" in python3.12

### ISSUE THREAD

**Issue by karltestano** [epoptes/epoptes#219]
Not using Epoptes for a long while, i found that it won't run under Linux Mint 24. My last usage was under Ubuntu 22.04.
Error was:
```
user@computer:~$ epoptes
Traceback (most recent call last):
  File "/usr/bin/epoptes", line 20, in <module>
    from epoptes.ui import gui
  File "/usr/lib/python3/dist-packages/epoptes/ui/gui.py", line 11, in <module>
    from distutils.version import Version
ModuleNotFoundError: No module named 'distutils'

```
System:
  Kernel: 6.8.0-41-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0 clocksource: tsc
  Desktop: Cinnamon v: 6.0.4 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Version:
epoptes        23.08-1      all          Computer lab management tool

Because i can't program in python i asked ChatGPT:

```
Q: replace distutils.version in epoptes /usr/lib/python3/dist-packages/epoptes/ui/gui.py
Answer:
sudo nano /usr/lib/python3/dist-packages/epoptes/ui/gui.py
Locate the distutils.version Import: Look for a line that imports distutils.version. It might look like this:
python
from distutils.version import LooseVersion
Replace with packaging.version: Change the import statement to use packaging.version. Modify it like this:
python
from packaging.version import Version

```
I also changed `LooseVersion` thru `Version` in the file.

And yes, it's running :-)

Thanks to the developers and would you be so kind and do this better than I?

**Comment by Dimitrysaf** [comment]
Install this package: 'python3-distutils-extra' it works
