### ISSUE TITLE
Epoptes service not starting on KDE Neon (Ubuntu 16.04)

### ISSUE THREAD

**Issue by wlc-asean** [Epoptes/epoptes#55]
At the end KDE Neon is just KDE on top of Ubuntu Xenial.

Here is a complete installation session... hope you can get something out of these info :
```
$ cat /etc/apt/epoptes-ubuntu-ppa-xenial.list

    deb http://ppa.launchpad.net/epoptes/ppa/ubuntu xenial main
```
```
$ sudo apt-get autoremove epoptes epoptes-client

    The following packages will be REMOVED:
        epoptes epoptes-client faketime iperf libfaketime libvncserver1 python-dbus python-netifaces python-notify python-pycha x11vnc x11vnc-data xvnc4viewer
```
```
$ sudo apt-get install --install-recommends epoptes epoptes-client

    The following NEW packages will be installed:
    epoptes epoptes-client faketime iperf libfaketime libvncserver1 python-dbus python-netifaces python-notify python-pycha x11vnc x11vnc-data xvnc4viewer

    Get:1  xenial-updates/main amd64 libvncserver1    amd64 0.9.10+dfsg-3ubuntu0.16.04.2 [122 kB]
    Get:2  xenial/universe     amd64 libfaketime      amd64 0.9.6-4 [22.0 kB]             
    Get:3  xenial/universe     amd64 faketime         amd64 0.9.6-4 [9,596 B]
    Get:4  xenial/universe     amd64 iperf            amd64 2.0.5+dfsg1-2 [51.0 kB]
    Get:5  xenial/main         amd64 python-dbus      amd64 1.2.0-3 [83.5 kB]
    Get:6  xenial/main         amd64 python-netifaces amd64 0.10.4-0.1build2 [16.7 kB]
    Get:7  xenial/universe     amd64 python-notify    amd64 0.1.1-4 [15.6 kB]
    Get:8  xenial/universe     amd64 python-pycha     all   0.7.0-2 [36.2 kB]
    Get:9  xenial/universe     amd64 x11vnc-data      all   0.9.13-1.2build1 [203 kB]
    Get:10 xenial/universe     amd64 x11vnc           amd64 0.9.13-1.2build1 [944 kB]
    Get:11 xenial/universe     amd64 xvnc4viewer      amd64 4.1.1+xorg4.3.0-37.3ubuntu2 [106 kB]
    Get:12 xenial/universe     amd64 epoptes          all   0.5.10-1 [182 kB]
    Get:13 xenial/universe     amd64 epoptes-client   all   0.5.10-1 [19.8 kB]
```
```
$ sudo /etc/init.d/epoptes start

    [ ok ] Starting epoptes (via systemctl): epoptes.service
```
```
$ sudo systemctl status epoptes

    epoptes.service - LSB: Epoptes service
    Loaded: loaded (/etc/init.d/epoptes; bad; vendor preset: enabled)
    Active: active (exited) since Tue 2018-05-08 13:16:33 +07; 4min 9s ago
        Docs: man:systemd-sysv-generator(8)

    May 08 13:16:33 phet-f02-03 epoptes[5501]:     procmon          A process watchdog / supervisor
    May 08 13:16:33 phet-f02-03 epoptes[5501]:     socks            A SOCKSv4 proxy service.
    May 08 13:16:33 phet-f02-03 epoptes[5501]:     web              A general-purpose web server which can serve from a
    May 08 13:16:33 phet-f02-03 epoptes[5501]:                      filesystem or application resource.
    May 08 13:16:33 phet-f02-03 epoptes[5501]:     words            A modern words server
    May 08 13:16:33 phet-f02-03 epoptes[5501]:     xmpp-router      An XMPP Router server
    May 08 13:16:33 phet-f02-03 epoptes[5501]: /usr/bin/twistd: Unknown command: epoptes
    May 08 13:16:33 phet-f02-03 epoptes[5501]:    ...done.
    May 08 13:16:33 phet-f02-03 systemd[1]: Started LSB: Epoptes service.
    May 08 13:20:15 phet-f02-03 systemd[1]: Started LSB: Epoptes service.
```
```
$ ps -ef | grep epoptes
$
```
```
$ sudo python /usr//lib/python2.7/dist-packages/twisted/plugins/epoptesd.py
    Traceback (most recent call last):
    File "/usr//lib/python2.7/dist-packages/twisted/plugins/epoptesd.py", line 32, in <module>
        from twisted.application import internet, service
    File "/usr/lib/python2.7/dist-packages/twisted/application/internet.py", line 54, in <module>
        from automat import MethodicalMachine
    File "/usr/lib/python2.7/dist-packages/automat/__init__.py", line 2, in <module>
        from ._methodical import MethodicalMachine
    File "/usr/lib/python2.7/dist-packages/automat/_methodical.py", line 34, in <module>
        @attr.s(frozen=True)
    TypeError: attributes() got an unexpected keyword argument 'frozen'
```
```
$ sudo twistd
  Unhandled Error
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 447, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 484, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 641, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 247, in _importAndCheckStack
    return __import__(importName)
  File "/usr/lib/python2.7/dist-packages/twisted/plugins/epoptesd.py", line 32, in <module>
    from twisted.application import internet, service
  File "/usr/lib/python2.7/dist-packages/twisted/application/internet.py", line 54, in <module>
    from automat import MethodicalMachine
  File "/usr/lib/python2.7/dist-packages/automat/__init__.py", line 2, in <module>
    from ._methodical import MethodicalMachine
  File "/usr/lib/python2.7/dist-packages/automat/_methodical.py", line 34, in <module>
    @attr.s(frozen=True)
exceptions.TypeError: attributes() got an unexpected keyword argument 'frozen'

Usage: twistd [options]
Options:
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
      --chroot=        Chroot to a supplied directory before running
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
  -e, --encrypted      The specified tap/aos file is encrypted.
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -f, --file=          read the given .tap file [default: twistd.tap]
  -g, --gid=           The gid to run as.
      --help           Display this help and exit.
      --help-reactors  Display a list of possibly available reactor names.
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
  -o, --no_save        do not save state on shutdown
      --originalname   Don't try to change the process name
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
  -s, --source=        Read an application from a .tas file (AOT format).
      --savestats      save the Stats object rather than the text output of the
                       profiler.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
      --syslog         Log to syslog, not to file
  -u, --uid=           The uid to run as.
      --umask=         The (octal) file creation mask to apply.
      --version        Print version information and exit.
  -y, --python=        read an application from within a Python file (implies
                       -o)

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch            A Conch SSH service.
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    mail             An email service
    manhole          An interactive remote debugger service accessible via
                     telnet and ssh and providing syntax coloring and basic line
                     editing functionality.
    news             A news server.
    portforward      A simple port-forwarder.
    procmon          A process watchdog / supervisor
    socks            A SOCKSv4 proxy service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.
    words            A modern words server
    xmpp-router      An XMPP Router server
$
```

As you can see, epoptes is not in the list of commands for twistd.

Willing to provide further info when needed.

**Comment by alkisg** [comment]
If you uninstall epoptes, and you run twistd again, does it still produce an "Unhandled Error"?

**Comment by wlc-asean** [comment]
Yes. I already tried that on two different Neon (Xenial) systems.

However, i could install and start epoptes without errors on a Ubuntu Server VM.

So I saved the list, with version and arch, of the installed packages for epoptes on the Ubuntu Server, and with that one I produced the same list on the Neon machine, in order to compare them.

Indeed I can see that the version of twisted is different between Ubuntu Server and Xenial. Respectively
- Ubuntu Server
    1. python-twisted-bin amd64 16.0.0-1ubuntu0.2
    2. python-twisted-core all 16.0.0-1ubuntu0.2

- Neon
    1. python-twisted-bin amd64 17.9.0-1+16.04+xenial+build1
    2. python-twisted-core all 17.9.0-1+16.04+xenial+build1

My question is then... what version of twisted are you targeting ?
Could that be the prob ?

**Comment by alkisg** [comment]
Epoptes runs on Ubuntu 18.04 with python-twisted 17.9.0-2 without issues.

Yours sounds like a problem in **another** of the packages that you have that use twisted, that it makes twisted produce the "Unhandled Error", and then twisted can't continue and load the rest of the ifs plugins, including epoptes.

So please solve the "Unhandled Error" first, and if the epoptes problem continues afterwards, then reopen this issue.

**Comment by alkisg** [comment]
This is not a problem in Xenial, as Xenial doesn't have the versions you're saying:
https://packages.ubuntu.com/search?suite=xenial&keywords=python-twisted

The problem is caused by KDE Neon, because it's modifying Ubuntu with incompatible libraries.
Distributions that do such things don't get official support status by Ubuntu...

**Comment by wlc-asean** [comment]
Going to report the bug to the KDE Neon list.
