### ISSUE TITLE
Application crashes in Ubuntu 18.04.01 LTS

### ISSUE THREAD

**Issue by GiorgosBetsos** [Epoptes/epoptes#71]
I've installed Ubuntu 18.04.01 LTS and then executed the scripts for the Greek School Network found 
at this link: http://ts.sch.gr/wiki/Linux/sch-scripts/%CE%95%CE%B3%CE%BA%CE%B1%CF%84%CE%AC%CF%83%CF%84%CE%B1%CF%83%CE%B7

Installation command: sh -c 'cd /tmp && wget ts.sch.gr/repo/sch-scripts && sh sch-scripts'

The application initially worked OK. After the first Ubuntu software update was applied the application no longer works. 

Instead it hangs and throws the following error:

Traceback (most recent call last):
  File "/usr/bin/epoptes", line 99, in <module>
    main()
  File "/usr/bin/epoptes", line 89, in main
    egui = gui.EpoptesGui()
  File "/usr/lib/python3/dist-packages/epoptes/ui/gui.py", line 118, in __init__
    config.expand_filename('groups.json'))
  File "/usr/lib/python3/dist-packages/epoptes/common/config.py", line 110, in read_groups
    data = json.loads(file.read())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by alkisg** [comment]
Hi Giorgos,

the best place for support for Greek schools is the forum:
http://alkisg.mysch.gr/steki/index.php?board=67.0

You may also find common issues and solutions for other software there.

To answer your question, it's probably a bad groups.json file (maybe zero size), and to clean epoptes settings and start over, run this from a terminal:
`rm -rf ~/.config/epoptes`
