### ISSUE TITLE
Epoptes doesn't start when groups.json is invalid

### ISSUE THREAD

**Issue by fottsia** [Epoptes/epoptes#82]
If ~/.config/epoptes/groups.json is invalid, e.g. empty, epoptes fails to start with no GUI messages.
If ran from the console, it gives:
```
Traceback (most recent call last):
  File "/usr/bin/epoptes", line 99, in <module>
    main()
  File "/usr/bin/epoptes", line 89, in main
    egui = gui.EpoptesGui()
  File "/usr/lib/python3/dist-packages/epoptes/ui/gui.py", line 118, in __init__
    config.expand_filename('groups.json'))
  File "/usr/lib/python3/dist-packages/epoptes/common/config.py", line 110, in read_groups
    data = json.loads(file.read())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

I think the best thing to do would be to recreate groups.json and start anyway, but to show a notice to the user that the file was corrupted.

**Comment by alkisg** [comment]
Thanks, fixed committed in https://github.com/Epoptes/epoptes/commit/209050866e7bacd4544c52c4719f0a1c349adfe3.
